<!--@meta
name: Home
 -->
<h1>Welcome to a PHP-generated page</h1>

<p>This page is generated by a PHP script in the content directory. PHP-generated content is marked as dynamic by default, and will not be cached.</p>

<p>Timestamp: <?php echo time(); ?></p>

<p>Random: <?php echo random_int(0, PHP_INT_MAX); ?></p>

<p><code>foo</code> GET parameter: <?php echo htmlentities($this->param('foo')); ?></p>

<p><a href="cacheable.html">Cacheable example page</a></p>

<?php
// $this->page()->setDynamic(false);
